### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [KmBarnett/mod_0_skills#1]
Hey Kyle! Overall good job on this assessment. We want you to make a few updates before we deem this a passing assessment. I've outlined the changes below. Let us know if you have questions on any of these. Please make these changes by end of day Monday. Thanks Kyle!

- [x] Make sure to choose a convention and stick with it for methods. Either parentheses or no parentheses, but not both. 
- [x] Find and fix any typos
- [x] Make sure your methods all clearly `change` or use an attribute to do some sort of calculation. We don't want you to simply use your method to return the value of your attribute.
- [x] For the cook method we don't need to see the temperature rising as part of the method, just the result. 
- [x] Make sure your commit messages are properly formatted.

**Comment by KmBarnett** [comment]
I made the changes I don't see any other typos but let me know if you do. I changed my methods and my attributes to better suit what you're looking for as well as I changed my commits messages I realized why I was doing any correctly. I remove the cook method temperatures that weren't necessary and I chose to go with parentheses.
